service: basic-serverless-lambda

provider:
  name: aws
  runtime: nodejs12.x
  stage: dev
  region: us-east-1

functions:
  hello:
    handler: SRC/handler.generateRamdonNumber
    timeout: 60 # seconds
    memorySize: 128 # mb
